services:
  server:
    build:
      context: .
      target: final
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8080:8080

  database:
    image: mysql:8.0
    ports:
      - 3307:3306
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: baleia123
      MYSQL_DATABASE: PokeShopDb
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -pbaleia123"]
      interval: 5s
      timeout: 10s
      retries: 10
volumes:
  db-data: